{{ $redis_master_replicas := attr "rc/redis-master/number" }}
{{ $container_name        := attr "rc/redis-master/name" }}
{{ $container_image       := attr "rc/redis-master/image" }}
{{ $container_version     := attr "rc/redis-master/version" }}
{{ $container_port        := attr "rc/redis-master/port" }}

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: {{ $redis_master_replicas }}
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: {{ $container_name }}
        image: {{ $container_image }}:{{ $container_version }}
        ports:
        - containerPort: {{ $container_port }}
