{{ $port := attr "svc/redis-master/port" }}

apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
    # the port that this service should serve on
  - port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: redis-master
